{
 "title": "AdGuard DNS Metrics",
 "description": "A dashboard for AdGuard DNS metrics.",
 "tags": [
  "dns",
  "adguard"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "metrics_start_time",
    "query": {
     "query": "query_result(scalar(min(agh_dns_queries_created)))"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(agh_dns_queries_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Queries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(agh_dns_queries_total{instance=~\"$instance\"})",
     "legendFormat": "Total Queries"
    }
   ]
  },
  {
   "title": "Blocked Query Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(agh_blocked_dns_queries_total{instance=~\"$instance\"}) / sum(agh_dns_queries_total{instance=~\"$instance\"}) * 100",
     "legendFormat": "Blocked Query Percentage"
    }
   ]
  },
  {
   "title": "Query types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (query_type) (agh_dns_query_types_total{instance=~\"$instance\"}) and on(query_type) (agh_dns_query_types_created{instance=~\"$instance\"} >= $metrics_start_time)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(agh_dns_queries_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Blocked Queries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(agh_blocked_dns_queries_total{instance=~\"$instance\"})",
     "legendFormat": "Blocked Queries"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(agh_dns_average_response_time{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time by upstream",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (server) (\r\n  agh_dns_average_upstream_response_time{instance=~\"$instance\"}\r\n  unless\r\n  (agh_dns_average_upstream_response_time{instance=~\"$instance\"} offset $__range)\r\n  == \r\n  ignoring(timestamp) \r\n  agh_dns_average_upstream_response_time{instance=~\"$instance\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 100 hosts",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(host) (agh_dns_query_hosts_total{instance=~\"$instance\"}) and on(host) (agh_dns_query_hosts_created{instance=~\"$instance\"} >= $metrics_start_time)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 100 blocked hosts",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "sum by(host) (agh_blocked_dns_query_hosts_total{instance=~\"$instance\"}) and on(host) (agh_blocked_dns_query_hosts_created{instance=~\"$instance\"} >= $metrics_start_time)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Safe search enforced",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "sum by (host) (agh_safe_search_enforced_hosts_total{instance=~\"$instance\"}) and on(host) (agh_safe_search_enforced_hosts_created{instance=~\"$instance\"} >= $metrics_start_time)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}